FROM node:lts AS builder

WORKDIR /araemisapp

ENV REACT_APP_BASENAME=/

COPY package.json .
COPY yarn.lock .

RUN yarn install

COPY . .

RUN yarn build

FROM nginx:stable

RUN rm -rf ./usr/share/nginx/html/*

COPY --from=builder /araemisapp/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx

EXPOSE 8080

CMD ["nginx","-g","daemon off;"]